/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_EPICETHERNETOUTPUT_PB_H_INCLUDED
#define PB_EPICETHERNETOUTPUT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DigitalOutput {
    int32_t numChannel;
    bool value;
} DigitalOutput;

typedef struct _EpicEthernetOutput {
    pb_callback_t digoutputs; /* 32 sorties [(nanopb).max_size = 32 , (nanopb).fixed_length = true] */
    int32_t nbChannel;
    pb_callback_t DeviceName; /*  */
    pb_callback_t MacAddress; /*  */
} EpicEthernetOutput;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DigitalOutput_init_default               {0, 0}
#define EpicEthernetOutput_init_default          {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define DigitalOutput_init_zero                  {0, 0}
#define EpicEthernetOutput_init_zero             {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define DigitalOutput_numChannel_tag             1
#define DigitalOutput_value_tag                  2
#define EpicEthernetOutput_digoutputs_tag        1
#define EpicEthernetOutput_nbChannel_tag         2
#define EpicEthernetOutput_DeviceName_tag        5
#define EpicEthernetOutput_MacAddress_tag        6

/* Struct field encoding specification for nanopb */
#define DigitalOutput_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    numChannel,        1) \
X(a, STATIC,   SINGULAR, BOOL,     value,             2)
#define DigitalOutput_CALLBACK NULL
#define DigitalOutput_DEFAULT NULL

#define EpicEthernetOutput_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  digoutputs,        1) \
X(a, STATIC,   SINGULAR, INT32,    nbChannel,         2) \
X(a, CALLBACK, SINGULAR, STRING,   DeviceName,        5) \
X(a, CALLBACK, SINGULAR, STRING,   MacAddress,        6)
#define EpicEthernetOutput_CALLBACK pb_default_field_callback
#define EpicEthernetOutput_DEFAULT NULL
#define EpicEthernetOutput_digoutputs_MSGTYPE DigitalOutput

extern const pb_msgdesc_t DigitalOutput_msg;
extern const pb_msgdesc_t EpicEthernetOutput_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DigitalOutput_fields &DigitalOutput_msg
#define EpicEthernetOutput_fields &EpicEthernetOutput_msg

/* Maximum encoded size of messages (where known) */
/* EpicEthernetOutput_size depends on runtime parameters */
#define DigitalOutput_size                       13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
