/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "epicethernetinput.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DigitalInput, DigitalInput, AUTO)


PB_BIND(AnalogInput, AnalogInput, AUTO)


PB_BIND(EpicEthernetInput, EpicEthernetInput, AUTO)



